import type { FurnitureCatalogItem } from "./types";

// All models are CC0: Kenney Furniture/Food kits (stylized) and Poly Haven (realistic).
// Licenses live next to the files in public/models/*.
const KENNEY = "/models/furniture";
const FOOD = "/models/food";
const polyhaven = (id: string) => `/models/polyhaven/${id}/${id}.gltf`;

const WARM_LIGHT = "#ffd9a0";

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
	// Sleep
	{
		id: "bed-queen",
		name: "Queen Bed",
		width: 1.6,
		depth: 2.0,
		height: 0.9,
		color: "#8d6e63",
		category: "Sleep",
		style: "stylized",
		model: `${KENNEY}/bedDouble.glb`,
	},
	{
		id: "bed-single",
		name: "Single Bed",
		width: 1.0,
		depth: 2.0,
		height: 0.85,
		color: "#a1887f",
		category: "Sleep",
		style: "stylized",
		model: `${KENNEY}/bedSingle.glb`,
	},
	{
		id: "bunk-bed",
		name: "Bunk Bed",
		width: 1.0,
		depth: 2.0,
		height: 1.6,
		color: "#a1887f",
		category: "Sleep",
		style: "stylized",
		model: `${KENNEY}/bedBunk.glb`,
	},
	{
		id: "nightstand",
		name: "Nightstand",
		width: 0.5,
		depth: 0.45,
		height: 0.55,
		color: "#8d6e63",
		category: "Sleep",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/cabinetBedDrawerTable.glb`,
	},

	// Living
	{
		id: "sofa",
		name: "Sofa",
		width: 1.8,
		depth: 0.85,
		height: 0.8,
		color: "#455a64",
		category: "Living",
		style: "stylized",
		model: `${KENNEY}/loungeSofa.glb`,
	},
	{
		id: "corner-sofa",
		name: "Corner Sofa",
		width: 2.2,
		depth: 2.2,
		height: 0.8,
		color: "#455a64",
		category: "Living",
		style: "stylized",
		model: `${KENNEY}/loungeSofaCorner.glb`,
	},
	{
		id: "lounge-chair",
		name: "Lounge Chair",
		width: 0.8,
		depth: 0.75,
		height: 0.8,
		color: "#607d8b",
		category: "Living",
		style: "stylized",
		model: `${KENNEY}/loungeChair.glb`,
	},
	{
		id: "bench",
		name: "Bench",
		width: 1.2,
		depth: 0.5,
		height: 0.85,
		color: "#8d6e63",
		category: "Living",
		style: "stylized",
		model: `${KENNEY}/bench.glb`,
	},
	{
		id: "coffee-table",
		name: "Coffee Table",
		width: 0.9,
		depth: 0.5,
		height: 0.4,
		color: "#4e342e",
		category: "Living",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/tableCoffee.glb`,
	},
	{
		id: "console-table",
		name: "Console Table",
		width: 0.9,
		depth: 0.4,
		height: 0.65,
		color: "#8d6e63",
		category: "Living",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/sideTable.glb`,
	},
	{
		id: "tv-unit",
		name: "TV Unit",
		width: 1.5,
		depth: 0.4,
		height: 0.55,
		color: "#37474f",
		category: "Living",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/cabinetTelevision.glb`,
	},
	{
		id: "sofa-fabric",
		name: "Fabric Sofa",
		width: 1.57,
		depth: 0.66,
		height: 0.8,
		color: "#7a6a5a",
		category: "Living",
		style: "realistic",
		model: polyhaven("Sofa_01"),
	},
	{
		id: "sofa-grand",
		name: "Grand Sofa",
		width: 2.73,
		depth: 0.93,
		height: 1.12,
		color: "#6b4f3a",
		category: "Living",
		style: "realistic",
		model: polyhaven("sofa_03"),
	},
	{
		id: "armchair",
		name: "Classic Armchair",
		width: 0.85,
		depth: 0.77,
		height: 1.07,
		color: "#7b5e45",
		category: "Living",
		style: "realistic",
		model: polyhaven("ArmChair_01"),
	},
	{
		id: "ottoman",
		name: "Ottoman",
		width: 0.88,
		depth: 0.62,
		height: 0.62,
		color: "#8b6f5a",
		category: "Living",
		style: "realistic",
		model: polyhaven("Ottoman_01"),
	},
	{
		id: "coffee-table-modern",
		name: "Modern Coffee Table",
		width: 1.2,
		depth: 0.6,
		height: 0.39,
		color: "#5d4a3a",
		category: "Living",
		style: "realistic",
		supports: true,
		model: polyhaven("modern_coffee_table_01"),
		modelYaw: 90,
	},
	{
		id: "side-table",
		name: "Round Side Table",
		width: 0.55,
		depth: 0.55,
		height: 0.45,
		color: "#6d5443",
		category: "Living",
		style: "realistic",
		supports: true,
		model: polyhaven("side_table_01"),
	},

	// Work
	{
		id: "study-table",
		name: "Study Table",
		width: 1.2,
		depth: 0.6,
		height: 0.75,
		color: "#795548",
		category: "Work",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/desk.glb`,
	},
	{
		id: "chair",
		name: "Desk Chair",
		width: 0.5,
		depth: 0.5,
		height: 0.9,
		color: "#6d4c41",
		category: "Work",
		style: "stylized",
		model: `${KENNEY}/chairDesk.glb`,
	},
	{
		id: "bookshelf",
		name: "Bookshelf",
		width: 0.8,
		depth: 0.35,
		height: 1.8,
		color: "#3e2723",
		category: "Work",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/bookcaseOpen.glb`,
	},
	{
		id: "books",
		name: "Books",
		width: 0.3,
		depth: 0.2,
		height: 0.2,
		color: "#b55d4c",
		category: "Work",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/books.glb`,
	},

	// Dining
	{
		id: "dining-table",
		name: "Dining Table",
		width: 1.6,
		depth: 0.9,
		height: 0.75,
		color: "#6d4c41",
		category: "Dining",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/table.glb`,
	},
	{
		id: "round-table",
		name: "Round Table",
		width: 1.0,
		depth: 1.1,
		height: 0.75,
		color: "#8d6e63",
		category: "Dining",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/tableRound.glb`,
	},
	{
		id: "dining-chair",
		name: "Dining Chair",
		width: 0.45,
		depth: 0.5,
		height: 0.9,
		color: "#795548",
		category: "Dining",
		style: "stylized",
		model: `${KENNEY}/chair.glb`,
	},
	{
		id: "bar-stool",
		name: "Bar Stool",
		width: 0.4,
		depth: 0.4,
		height: 0.75,
		color: "#8d6e63",
		category: "Dining",
		style: "stylized",
		model: `${KENNEY}/stoolBar.glb`,
	},

	// Storage
	{
		id: "wardrobe",
		name: "Wardrobe",
		width: 1.2,
		depth: 0.6,
		height: 2.0,
		color: "#5d4037",
		category: "Storage",
		style: "stylized",
		model: `${KENNEY}/bookcaseClosedDoors.glb`,
	},
	{
		id: "coat-rack",
		name: "Coat Rack",
		width: 0.5,
		depth: 0.5,
		height: 1.75,
		color: "#8d6e63",
		category: "Storage",
		style: "stylized",
		model: `${KENNEY}/coatRackStanding.glb`,
	},
	{
		id: "trash-can",
		name: "Trash Can",
		width: 0.3,
		depth: 0.3,
		height: 0.55,
		color: "#9e9e9e",
		category: "Storage",
		style: "stylized",
		model: `${KENNEY}/trashcan.glb`,
	},
	{
		id: "drawer-cabinet",
		name: "Drawer Cabinet",
		width: 1.14,
		depth: 0.49,
		height: 1.88,
		color: "#6d5443",
		category: "Storage",
		style: "realistic",
		supports: true,
		model: polyhaven("drawer_cabinet"),
	},

	// Lighting
	{
		id: "floor-lamp",
		name: "Floor Lamp",
		width: 0.35,
		depth: 0.35,
		height: 1.7,
		color: "#c49a52",
		category: "Lighting",
		style: "stylized",
		model: `${KENNEY}/lampRoundFloor.glb`,
		light: { color: WARM_LIGHT, intensity: 3, material: "lamp" },
	},
	{
		id: "floor-lamp-square",
		name: "Square Floor Lamp",
		width: 0.3,
		depth: 0.3,
		height: 1.6,
		color: "#c49a52",
		category: "Lighting",
		style: "stylized",
		model: `${KENNEY}/lampSquareFloor.glb`,
		light: { color: WARM_LIGHT, intensity: 3, material: "lamp" },
	},
	{
		id: "desk-lamp",
		name: "Desk Lamp",
		width: 0.18,
		depth: 0.18,
		height: 0.45,
		color: "#c49a52",
		category: "Lighting",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/lampSquareTable.glb`,
		light: { color: WARM_LIGHT, intensity: 1.2, material: "lamp" },
	},
	{
		id: "table-lamp",
		name: "Table Lamp",
		width: 0.3,
		depth: 0.3,
		height: 0.5,
		color: "#c49a52",
		category: "Lighting",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/lampRoundTable.glb`,
		light: { color: WARM_LIGHT, intensity: 1.5, material: "lamp" },
	},
	{
		id: "ceiling-fan",
		name: "Ceiling Fan",
		width: 1.2,
		depth: 1.2,
		height: 0.3,
		color: "#bdbdbd",
		category: "Lighting",
		style: "stylized",
		mount: "ceiling",
		model: `${KENNEY}/ceilingFan.glb`,
		light: { color: WARM_LIGHT, intensity: 4, material: "lamp" },
	},
	{
		id: "desk-lamp-arm",
		name: "Arm Desk Lamp",
		width: 0.2,
		depth: 0.61,
		height: 0.89,
		color: "#3a3a3a",
		category: "Lighting",
		style: "realistic",
		mount: "surface",
		model: polyhaven("desk_lamp_arm_01"),
		light: {
			color: WARM_LIGHT,
			intensity: 1.5,
			material: "desk_lamp_arm_01_light",
		},
	},
	{
		id: "pendant-lamp",
		name: "Pendant Lamp",
		width: 0.43,
		depth: 0.43,
		height: 0.95,
		color: "#d6d0c4",
		category: "Lighting",
		style: "realistic",
		mount: "ceiling",
		model: polyhaven("modern_ceiling_lamp_01"),
		light: {
			color: WARM_LIGHT,
			intensity: 5,
			material: "modern_ceiling_globe",
		},
	},

	// Electronics
	{
		id: "tv-flat",
		name: "Flat TV",
		width: 1.2,
		depth: 0.12,
		height: 0.75,
		color: "#263238",
		category: "Electronics",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/televisionModern.glb`,
	},
	{
		id: "tv-vintage",
		name: "Vintage TV",
		width: 0.6,
		depth: 0.4,
		height: 0.45,
		color: "#6d4c41",
		category: "Electronics",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/televisionVintage.glb`,
	},
	{
		id: "monitor",
		name: "Monitor",
		width: 0.6,
		depth: 0.18,
		height: 0.45,
		color: "#263238",
		category: "Electronics",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/computerScreen.glb`,
	},
	{
		id: "keyboard",
		name: "Keyboard",
		width: 0.44,
		depth: 0.15,
		height: 0.03,
		color: "#37474f",
		category: "Electronics",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/computerKeyboard.glb`,
	},
	{
		id: "laptop",
		name: "Laptop",
		width: 0.34,
		depth: 0.3,
		height: 0.22,
		color: "#90a4ae",
		category: "Electronics",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/laptop.glb`,
	},
	{
		id: "radio",
		name: "Radio",
		width: 0.35,
		depth: 0.12,
		height: 0.25,
		color: "#8d6e63",
		category: "Electronics",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/radio.glb`,
	},
	{
		id: "speaker",
		name: "Floor Speaker",
		width: 0.25,
		depth: 0.25,
		height: 1.0,
		color: "#5d4037",
		category: "Electronics",
		style: "stylized",
		model: `${KENNEY}/speaker.glb`,
	},
	{
		id: "tv-retro",
		name: "Retro TV",
		width: 0.6,
		depth: 0.47,
		height: 0.46,
		color: "#5d4a3a",
		category: "Electronics",
		style: "realistic",
		mount: "surface",
		model: polyhaven("Television_01"),
	},

	// Decor
	{
		id: "plant",
		name: "Indoor Plant",
		width: 0.45,
		depth: 0.45,
		height: 1.2,
		color: "#4f7942",
		category: "Decor",
		style: "stylized",
		model: `${KENNEY}/pottedPlant.glb`,
	},
	{
		id: "plant-small",
		name: "Small Plant",
		width: 0.18,
		depth: 0.18,
		height: 0.28,
		color: "#4f7942",
		category: "Decor",
		style: "stylized",
		mount: "surface",
		model: `${KENNEY}/plantSmall1.glb`,
	},
	{
		id: "rug",
		name: "Area Rug",
		width: 2.0,
		depth: 1.4,
		height: 0.02,
		color: "#b98275",
		category: "Decor",
		style: "stylized",
		model: `${KENNEY}/rugRectangle.glb`,
	},
	{
		id: "teddy-bear",
		name: "Animal Trophy",
		width: 0.35,
		depth: 0.22,
		height: 0.4,
		color: "#a1887f",
		category: "Decor",
		style: "stylized",
		mount: "wall",
		wallHeight: 1.6,
		model: `${KENNEY}/bear.glb`,
	},
	{
		id: "vase",
		name: "Ceramic Vase",
		width: 0.2,
		depth: 0.2,
		height: 0.4,
		color: "#c9b79c",
		category: "Decor",
		style: "realistic",
		mount: "surface",
		model: polyhaven("ceramic_vase_01"),
	},
	{
		id: "plant-potted",
		name: "Potted Succulent",
		width: 0.17,
		depth: 0.18,
		height: 0.27,
		color: "#5a7d4a",
		category: "Decor",
		style: "realistic",
		mount: "surface",
		model: polyhaven("potted_plant_04"),
	},
	{
		id: "picture-frame",
		name: "Picture Frame",
		width: 0.2,
		depth: 0.1,
		height: 0.25,
		color: "#8d6e63",
		category: "Decor",
		style: "realistic",
		mount: "wall",
		wallHeight: 1.4,
		model: polyhaven("standing_picture_frame_01"),
		modelYaw: -90,
	},
	{
		id: "alarm-clock",
		name: "Alarm Clock",
		width: 0.13,
		depth: 0.07,
		height: 0.17,
		color: "#b0463c",
		category: "Decor",
		style: "realistic",
		mount: "surface",
		model: polyhaven("alarm_clock_01"),
	},

	// Kitchen
	{
		id: "fridge",
		name: "Fridge",
		width: 0.7,
		depth: 0.65,
		height: 1.8,
		color: "#eceff1",
		category: "Kitchen",
		style: "stylized",
		model: `${KENNEY}/kitchenFridge.glb`,
	},
	{
		id: "washer",
		name: "Washing Machine",
		width: 0.6,
		depth: 0.6,
		height: 0.85,
		color: "#eceff1",
		category: "Kitchen",
		style: "stylized",
		supports: true,
		model: `${KENNEY}/washer.glb`,
	},
	{
		id: "mug",
		name: "Mug",
		width: 0.12,
		depth: 0.1,
		height: 0.1,
		color: "#e57373",
		category: "Kitchen",
		style: "stylized",
		mount: "surface",
		model: `${FOOD}/mug.glb`,
	},
	{
		id: "plate",
		name: "Plate",
		width: 0.27,
		depth: 0.27,
		height: 0.03,
		color: "#f5f5f5",
		category: "Kitchen",
		style: "stylized",
		mount: "surface",
		model: `${FOOD}/plate.glb`,
	},
	{
		id: "wine-bottle",
		name: "Wine Bottle",
		width: 0.08,
		depth: 0.08,
		height: 0.3,
		color: "#6d2b3a",
		category: "Kitchen",
		style: "stylized",
		mount: "surface",
		model: `${FOOD}/wine-red.glb`,
	},
];

export function getCatalogItem(catalogId: string): FurnitureCatalogItem {
	const item = FURNITURE_CATALOG.find((c) => c.id === catalogId);
	if (!item) throw new Error(`Unknown catalog item: ${catalogId}`);
	return item;
}
