import type { FurnitureCatalogItem } from "./types";

// 3D models: Kenney Furniture Kit (CC0) — see public/models/furniture/LICENSE-kenney.txt.
const MODELS = "/models/furniture";

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
	{
		id: "bed-queen",
		name: "Queen Bed",
		width: 1.6,
		depth: 2.0,
		height: 0.9,
		color: "#8d6e63",
		model: `${MODELS}/bedDouble.glb`,
	},
	{
		id: "bed-single",
		name: "Single Bed",
		width: 1.0,
		depth: 2.0,
		height: 0.85,
		color: "#a1887f",
		model: `${MODELS}/bedSingle.glb`,
	},
	{
		id: "wardrobe",
		name: "Wardrobe",
		width: 1.2,
		depth: 0.6,
		height: 2.0,
		color: "#5d4037",
		model: `${MODELS}/bookcaseClosedDoors.glb`,
	},
	{
		id: "study-table",
		name: "Study Table",
		width: 1.2,
		depth: 0.6,
		height: 0.75,
		color: "#795548",
		model: `${MODELS}/desk.glb`,
	},
	{
		id: "chair",
		name: "Chair",
		width: 0.5,
		depth: 0.5,
		height: 0.9,
		color: "#6d4c41",
		model: `${MODELS}/chairDesk.glb`,
	},
	{
		id: "sofa",
		name: "Sofa",
		width: 1.8,
		depth: 0.85,
		height: 0.8,
		color: "#455a64",
		model: `${MODELS}/loungeSofa.glb`,
	},
	{
		id: "coffee-table",
		name: "Coffee Table",
		width: 0.9,
		depth: 0.5,
		height: 0.4,
		color: "#4e342e",
		model: `${MODELS}/tableCoffee.glb`,
	},
	{
		id: "bookshelf",
		name: "Bookshelf",
		width: 0.8,
		depth: 0.35,
		height: 1.8,
		color: "#3e2723",
		model: `${MODELS}/bookcaseOpen.glb`,
	},
	{
		id: "nightstand",
		name: "Nightstand",
		width: 0.5,
		depth: 0.45,
		height: 0.55,
		color: "#8d6e63",
		model: `${MODELS}/cabinetBedDrawerTable.glb`,
	},
	{
		id: "dining-table",
		name: "Dining Table",
		width: 1.6,
		depth: 0.9,
		height: 0.75,
		color: "#6d4c41",
		model: `${MODELS}/table.glb`,
	},
	{
		id: "dining-chair",
		name: "Dining Chair",
		width: 0.45,
		depth: 0.5,
		height: 0.9,
		color: "#795548",
		model: `${MODELS}/chair.glb`,
	},
	{
		id: "tv-unit",
		name: "TV Unit",
		width: 1.5,
		depth: 0.4,
		height: 0.55,
		color: "#37474f",
		model: `${MODELS}/cabinetTelevision.glb`,
	},
	{
		id: "floor-lamp",
		name: "Floor Lamp",
		width: 0.35,
		depth: 0.35,
		height: 1.7,
		color: "#c49a52",
		model: `${MODELS}/lampRoundFloor.glb`,
		light: { color: "#ffd9a0", intensity: 3 },
	},
	{
		id: "plant",
		name: "Indoor Plant",
		width: 0.45,
		depth: 0.45,
		height: 1.2,
		color: "#4f7942",
		model: `${MODELS}/pottedPlant.glb`,
	},
	{
		id: "rug",
		name: "Area Rug",
		width: 2.0,
		depth: 1.4,
		height: 0.02,
		color: "#b98275",
		model: `${MODELS}/rugRectangle.glb`,
	},
];

export function getCatalogItem(catalogId: string): FurnitureCatalogItem {
	const item = FURNITURE_CATALOG.find((c) => c.id === catalogId);
	if (!item) throw new Error(`Unknown catalog item: ${catalogId}`);
	return item;
}
